### PR TITLE
adding -y/--yes as alias for -c/--confirm

### PR DESCRIPTION
**Pull request by esc**
Yes, I know there are no test and the redundency is pretty crazy, but it works!

Ideally:

* Add command line tests using cram.
* Refactor the command line handing to have all options specified once and once
  only.

### CODE REVIEW

**Comment by esc** [comment]
@marco-hoyer would you be willing to accept this change?

**Comment by marco-hoyer** [comment]
I'm not sure about this. Personally I don't like the idea to have identical switches for one value/function/meaning. The -y/--yes flag might be easier. What is your need here?

**Comment by esc** [comment]
Just people complaining about a missing `-y/--yes` flag and then ranting when they discover `-c/--confirm`.

**Comment by esc** [comment]
ty

**Pull request merged**
