### PR TITLE
Python 3 port

### PR DESCRIPTION
**Pull request by philipppahl**
Try ... except ImportError statements in unittests to run with Python 3.

### CODE REVIEW

**Comment by esc** [comment]
Is this just for convenience or did it block you in any way?

I am asking because currently we don't have a way in PyBuilder to make python version specific dependencies available from the generated `setup.py`. This means, that in any case `unittest2` and `mock` will be installed regardless of the Python version if you install cfn-sphere from PyPi. Further work is required in PyBuilder to enable such features.

**Comment by esc** [comment]
And thanks for your contribution @philipppahl , nice to see some external contributions happening! :)

**Comment by marco-hoyer** [comment]
@philipppahl thanks for that. Where did you see problems with those imports? We're running the tests with TravisCI for python2 and python3 without any errors so far.

**Comment by philipppahl** [comment]
Huh, I got a package conflict, when I tried to conda-install unittest2 with python 3.5. With ``pyb install_dependencies`` everything works fine. It's not blocking me, just for convenience.

**Comment by marco-hoyer** [comment]
I'm not sure about this. Didn't use condo before. @cfn-sphere/contributors and other suggestions here?

**Comment by esc** [comment]
`conda` is a third-party package manager. Maybe when we have the optional dependencies feature in PyBuilder it would make sense. So I would suggest to merge this now and reap the advantages later.

**Comment by marco-hoyer** [comment]
ok :-)

**Pull request merged**
