### PR TITLE
Added change_set command.

### PR DESCRIPTION
**Pull request by rayhwang-kcom**
Todo:
 - Clean up when done with change set
 - Format changeset output
 - Error handling
 - Handle new stacks

### CODE REVIEW

**Comment by marco-hoyer** [comment]
Hi, sorry for the delay. I'm a bit busy these days. Could you please review the Travis CI results. Your changes seem to break builds for some python versions.

**Comment by h1f1x** [comment]
@rayhwangkcom , could you fix the small, but easy to fix parts of the code, mentioned in the code-quality checker, please?

**Comment by rayhwangkcom** [comment]
@h1f1x - I've removed the unused parameter 'stack'.

The 'use %...' change I did not implement as it's what the existing code uses and changing it would mean that the code itself is no longer consistent.

**Comment by rayhwangkcom** [comment]
Hi,

Will be really appreciated if someone can have a look at this (and make the output nicer perhaps) and release the feature?

**Comment by rayhwangkcom** [comment]
Hi - any updates on this?

**Comment by marco-hoyer** [comment]
Hi, I'm really busy these days so I was not able to have a deeper look at this. It still seems as if there are problems with the travis build. I am also still not sure if this fits the concept of this application.

**Pull request closed without merging**
