### PR TITLE
Concurrent execution of sync/delete operations, see #117

### PR DESCRIPTION
**Pull request by konz**
Following up on the discussion in #117

The idea is operate on a list of `execution` objects that are processed sequentially, just as of now. But these executions contain one or more stacks that can be executed concurrently. 

Iterating on the executions and creating one thread per stack withtin an execution is still missing.

I also cleaned up the test stacks a bit, hope I didn't miss anything

### CODE REVIEW

**Comment by konz** [comment]
There is `sync -x` now to switch to concurrent execution. Should work! :-) But needs some cleanup and more tests

**Comment by konz** [comment]
Also errors during concurrent execution might be not bubbling up

**Comment by konz** [comment]
Note to self: service roles and stack policies did not survive merging

**Comment by konz** [comment]
Things still to be done:

- [ ] restore service roles and stack policies
- [ ] proper test coverage for [create_or_update.py](konz/cfn-sphere/blob/parallel_execution/src/main/python/cfn_sphere/create_or_update.py)
- [ ] nicer error handling in concurrent execution. Errors do pop up but are not handled
- [ ] interrupt concurrent execution when main thread is interrupted e.g. by pressing `^C`
- [ ] implement concurrency for stack deletion

@cfn-sphere/contributors what do you think so far?

**Comment by marco-hoyer** [comment]
I think this is too old to merge it.

**Pull request closed without merging**
