### PR TITLE
adding initial snakepit.yaml file

### PR DESCRIPTION
**Pull request by esc**
Consolidating the snakepit.yaml file that I found elsewhere. This will allow us
to better automate RPM-Building.

### CODE REVIEW

**Comment by esc** [comment]
cc @schlomo

**Comment by esc** [comment]
The project version when building in the `teamcity` environment.. still contains a `-` so this may be a problem when building RPMs. I don't think we currently use this anywhere and that this has been copied and pasted from a template. Let me change it.

**Comment by esc** [comment]
let's hold off on this one, it's a can of worms..

**Comment by marco-hoyer** [comment]
what about this? shall we close it?

**Comment by esc** [comment]
You can, yeah, if you don't need it

On 12 July 2016 09:50:32 CEST, Marco Hoyer <notifications@github.com> wrote:
>what about this? shall we close it?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cfn-sphere/cfn-sphere/pull/73#issuecomment-231964565

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request closed without merging**
